# Generated by Django 2.0.7 on 2018-08-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180820_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
    ]
