# Generated by Django 2.0.7 on 2018-08-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180825_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.FileField(blank=True, null=True, upload_to='page'),
        ),
    ]
